services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres_wa_finance
    restart: always
    environment:
      POSTGRES_DB: db_wa_finance
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_wa_finance
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  wuzapi:
    image: asternic/wuzapi:latest
    container_name: wuzapi
    ports:
      - "8080:8080"
    environment:
      - WUZAPI_ADMIN_TOKEN=chavesecretacabulosa2000
      - TZ=America/Sao_Paulo
      - WEBHOOK_FORMAT=json
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
  evolution_instances: