spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_wa_finance
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgrespassword}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASS:adminpassword}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo

server:
  port: 8080