spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_wa_finance
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASS:adminpassword}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true

management:
  endpoints:
    web:
      exposure:
        include: health

app:
  security:
    phone-key: ${PHONE_ENCRYPTION_KEY}
