server:
  port: 8080

spring:
  application:
    name: ai-service

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: adminpassword

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.0

app:
  financial-service:
    url: ${APP_FINANCIAL_SERVICE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health
