package com.whatsapp_service.flow;

public enum WhatsAppAction {
    ABRIR_MENU,
    REGISTRAR_GASTO,
    VER_RELATORIO,
    MAIS_OPCOES,
    GERENCIAR_CATEGORIAS,
    LISTAR_CATEGORIAS,
    CRIAR_CATEGORIA,
    DESATIVAR_CATEGORIA,
    CONFIRMAR_DESATIVACAO_CATEGORIA,
    CANCELAR_FLUXO,
    AJUDA,
    VOLTAR_MENU,
    CANCELAR_TRANSACAO,
    TEXTO_LIVRE
}
