server:
  port: 8080

spring:
  application:
    name: whatsapp-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
wuzapi:
  url: ${WUZAPI_BASE_URL}
  token: ${AUTHENTICATION_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health
